<a href="https://colab.research.google.com/github/2303A51528/PDS_1528/blob/main/22aug%20assmnt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Generate a 4x4 array with test scores (values between 50-100 for realism)
np.random.seed(42)  # for reproducibility
scores = np.random.randint(50, 101, size=(4, 4))
print("Test Scores (4x4 Matrix):\n", scores)

# Row-wise and Column-wise Means
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)

print("\nRow-wise Means:", row_means)
print("Column-wise Means:", col_means)

# Standard Deviation and Variance
std_dev = np.std(scores)
variance = np.var(scores)

print("\nStandard Deviation:", std_dev)
print("Variance:", variance)

# Global Max, Min and their Indices
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)

print("\nGlobal Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index)

# Median values
row_medians = np.median(scores, axis=1)
col_medians = np.median(scores, axis=0)
global_median = np.median(scores)

print("\nRow-wise Medians:", row_medians)
print("Column-wise Medians:", col_medians)
print("Global Median:", global_median)


Test Scores (4x4 Matrix):
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]]

Row-wise Means: [80.5  70.75 66.25 74.75]
Column-wise Means: [75.5  74.25 71.25 71.25]

Standard Deviation: 12.214073593605043
Variance: 149.18359375

Global Max: 92 at index (np.int64(0), np.int64(3))
Global Min: 52 at index (np.int64(3), np.int64(3))

Row-wise Medians: [83. 69. 66. 79.]
Column-wise Medians: [78.5 74.  68.5 70.5]
Global Median: 72.5
