<a href="https://colab.research.google.com/github/2303A51528/PDS_1528/blob/main/assignment%203%20-22aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr2d = np.array([[1, 2, 3],[4, 5, 6]])
arr1d = np.array([10, 20, 30])
print("2D Array:\n", arr2d)
print("1D Array:\n", arr1d)
print("2D + 1D Broadcasting:\n", arr2d + arr1d)

print("Shapes -> 2D:", arr2d.shape, ", 1D:", arr1d.shape)

arr3d = np.ones((2, 3, 4))
scalar = 5
print("\n3D Array shape:", arr3d.shape)
print("Scalar:", scalar)
print("3D + Scalar Broadcasting:\n", arr3d + scalar)

arr_col = np.array([1, 2])[:, np.newaxis]
print("\nOriginal 2D:\n", arr2d)
print("Column Vector Shape:", arr_col.shape)
print("Broadcasting with newaxis:\n", arr2d + arr_col)

try:
    invalid = np.array([1, 2, 3, 4])
    print("\nInvalid Broadcasting Attempt:\n", arr2d + invalid)
except ValueError as e:
    print("\nInvalid Broadcasting Error:", e)


2D Array:
 [[1 2 3]
 [4 5 6]]
1D Array:
 [10 20 30]
2D + 1D Broadcasting:
 [[11 22 33]
 [14 25 36]]
Shapes -> 2D: (2, 3) , 1D: (3,)

3D Array shape: (2, 3, 4)
Scalar: 5
3D + Scalar Broadcasting:
 [[[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]

 [[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]]

Original 2D:
 [[1 2 3]
 [4 5 6]]
Column Vector Shape: (2, 1)
Broadcasting with newaxis:
 [[2 3 4]
 [6 7 8]]

Invalid Broadcasting Error: operands could not be broadcast together with shapes (2,3) (4,) 


In [5]:
'''2'''

'2'

In [4]:
import numpy as np

arr = np.array([[4, -9, 16],[25, -36, 49]])

print("Original Array:\n", arr)

squared = np.square(arr)
print("\nSquared:\n", squared)

sqrted = np.sqrt(np.abs(arr))
print("\nSquare Root (absolute values):\n", sqrted)

replaced = np.where(arr < 0, 0, arr)
print("\nNegative Replaced with 0:\n", replaced)

count_gt10 = np.sum(arr > 10)
print("\nCount of elements > 10:", count_gt10)

mask = arr > 10
print("\nMask for condition > 10:\n", mask)

print("\nArray elements > 10:\n", arr[mask])


Original Array:
 [[  4  -9  16]
 [ 25 -36  49]]

Squared:
 [[  16   81  256]
 [ 625 1296 2401]]

Square Root (absolute values):
 [[2. 3. 4.]
 [5. 6. 7.]]

Negative Replaced with 0:
 [[ 4  0 16]
 [25  0 49]]

Count of elements > 10: 3

Mask for condition > 10:
 [[False False  True]
 [ True False  True]]

Array elements > 10:
 [16 25 49]
