<a href="https://colab.research.google.com/github/2303A51528/PDS_1528/blob/main/lab2%20assmnt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
student_marks = np.random.randint(0, 101, size=(10, 3))
print(student_marks)

[[94 84 47]
 [22 97 14]
 [70 23  4]
 [50 34 62]
 [85 35 99]
 [31 31 49]
 [72 25 21]
 [ 5 82 44]
 [51  3 17]
 [22 78 34]]


In [3]:
overall_average = np.mean(student_marks)
overall_minimum = np.min(student_marks)
overall_maximum = np.max(student_marks)
print(f"Overall Average Mark: {overall_average:.2f}")
print(f"Overall Minimum Mark: {overall_minimum}")
print(f"Overall Maximum Mark: {overall_maximum}")

Overall Average Mark: 46.17
Overall Minimum Mark: 3
Overall Maximum Mark: 99


In [6]:
first_three=student_marks[:3, :]
print("Marks of the first three students:")
print(first_three_students_marks)
student_at_index_5_marks = student_marks[5, :]
print("\nMarks of the student at index 5:")
print(student_at_index_5_marks)

Marks of the first three students:
[[94 84 47]
 [22 97 14]
 [70 23  4]]

Marks of the student at index 5:
[31 31 49]


In [9]:
high_scoring_students = student_marks[np.any(student_marks > 80, axis=1)]

print("\nStudents scoring above 80 in at least one subject:")
print(high_scoring_students)


Students scoring above 80 in at least one subject:
[[94 84 47]
 [22 97 14]
 [85 35 99]
 [ 5 82 44]]


In [8]:
subject_wise_marks = student_marks.T

print("\nSubject-wise Marks Array (transposed):")
print(subject_wise_marks)
subject_average_marks = np.mean(subject_wise_marks, axis=1)
subject_minimum_marks = np.min(subject_wise_marks, axis=1)
subject_maximum_marks = np.max(subject_wise_marks, axis=1)

print("\nSubject-wise Average Marks:")
print(subject_average_marks)

print("\nSubject-wise Minimum Marks:")
print(subject_minimum_marks)

print("\nSubject-wise Maximum Marks:")
print(subject_maximum_marks)


Subject-wise Marks Array (transposed):
[[94 22 70 50 85 31 72  5 51 22]
 [84 97 23 34 35 31 25 82  3 78]
 [47 14  4 62 99 49 21 44 17 34]]

Subject-wise Average Marks:
[50.2 49.2 39.1]

Subject-wise Minimum Marks:
[5 3 4]

Subject-wise Maximum Marks:
[94 97 99]
